---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wireshark
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: lscr.io/linuxserver/wireshark
      tag: 4.0.6
    # https://github.com/linuxserver/docker-wireshark
    env:
      TZ: "${TIMEZONE}"
      PUID: "${PUID}"
      PGID: "${PGID}"
    service:
      main:
        ports:
          http:
            port: 3000
    securityContext:
      seccompProfile:
        type: Unconfined
      capabilities:
        add: [NET_ADMIN]
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: wireshark-appdata
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:shark
        hosts:
          - host: &host "wireshark.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
