---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireshark-appdata-new
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-app
  resources:
    requests:
      storage: 1G
