kind: ENC[AES256_GCM,data:M+UNiaro,iv:zas0yNvxXNHSPgIDmFwSxBgodbsMxAM8qwRBGf+cbMM=,tag:jxR8lOowXv0KmjDZLrPuyQ==,type:str]
ansible_user: ENC[AES256_GCM,data:vH0kyUd8Vw+3,iv:F8IdikPHvuluFl2qG06ickIE0VXid67GKry819CGVXs=,tag:SaM510hQqhuerOKCmWirJA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:CJ7+IYxdyrxnucc=,iv:QQ3wTrrk7qZ8zsbBOY5ut6PKJX7HdSvt1xMaU9IfQLM=,tag:QjKAWwFUwZMure3jsS1owA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNkpadnhzemNDcVk1cHQ0
            YXNaTm5JQTk4ZzZaaXNCWk85eU9UWnE1dFEwCmVjMUE0b0lIdld4R3MrOVNtYlNa
            ZFB6TDcrNHhOdzFNWSt4alAyNlpYZE0KLS0tIHZVUWhrNW1ZM00vemcwdzdSanB4
            a2U4ckRKc20wSko5QmJlUU5Wb0p4RkEKfFtfqQ9aB67h9t8YrPGTMlykvHyocGYo
            Q4s2reWm6NvK3i/S4j/w3F7eGklRvHI8bQzJhznR0DS5t7XmbYZ4cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T19:42:10Z"
    mac: ENC[AES256_GCM,data:jy4QBMyJDR5hJyZHhj66baGSzPyAWzwinvhw/IIfQj0kQItMsJBgziPBfbgEqMwyGLkaNA9XLSo4kria3ZvlLoTIsARV4gR5miAjfiOP2HeagCD6w4f2NiaktW4c+40AEDE45Zgotyix2v2ukhHyTbKsWaeLQb/KnBdZyvUn1eM=,iv:HJKEcSmLCJ0H/5170xexq6WdLUG+dAyV/lsWx4b6xT8=,tag:Y26xM76c6zt2DIAFIDrFtg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
