kind: ENC[AES256_GCM,data:9fMiU6oh,iv:U8hELqZExyH10zLWdPuoAqHCJFb4r2dmRhBmdxySDuM=,tag:2lxwuvsklZ1wZSUSUsvnTQ==,type:str]
ansible_user: ENC[AES256_GCM,data:/X6otbFcFOgH,iv:iVfxu1n9eqpcMA6pRBA9wHcpZGJ2JnAkwPYusdBzwWY=,tag:zHJw7VVcyIY4yABaKnLSLg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:BgIzdOjyiVfEWlM=,iv:KLZ05GMhGS436j6uETSp3uLQOywNbkZ1ejPHDAAJdS0=,tag:nz37Zd2LtD4Vuy8IxRGOwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMXp3cld4S01Pc2ZWV3dH
            TW96blhUTmM5N1J4OXZST3pCVE9XQ3FEb2h3CjBBWFZRQXpuM2FERUUwSndzZTZx
            ZS9QbHdaLzZic1NjVmorOHFYeGEraVUKLS0tIFJDNXdMc05aSGdjcENDcnJSN1Bi
            ZCtac1loWjFBVGFEMTR2dURnZVZXN2cKjPfAcipdzA31E16JRr/PISA0aqIdxhKb
            8yRiSdcnJ078PP9NEXaNoI8cUfuxngGEZP05zDytyeJGM8Yoi8OQBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T19:42:10Z"
    mac: ENC[AES256_GCM,data:It6IFuIfx5dXQ1WBYP0kRP5Zr31tBjXJdSevgZt0A7UKgDBPu5wTD7sW3vm/3LhoJ8fJKcf9GIi9KHMtC6zoH4SXuke/ZBwKfjv3mgNji0MBn6MhyLpFlajtoiwoCeIPP6ZBFo9N8c6p6JTiZWHAMravIgJGCRgzy/obLkgeRH4=,iv:HgfZwzEADXdr43IgCGsBIWy97bunW0CbioU/Q+WV5jg=,tag:6oUEQrTOBfk2xOxcirbNtA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
