kind: ENC[AES256_GCM,data:iV3nPlBP,iv:sEJIOCtr2td2X4c/f4Ie6rT06YVE0dGf7RL4T6u2sno=,tag:F84ivTDN0+zK7yi9XpSY6g==,type:str]
ansible_user: ENC[AES256_GCM,data:Uu4xPT5kxRk9,iv:Ct7ldf3RO0WlArJ03sIzn7IA/zrTDu579OLYcUBicho=,tag:Z+WDwwHaEl+W6qAWY7Mc2g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:0seIX8NJ02A9/Bs=,iv:8+7K48GeM4y5gJHfatWCjNhKCols5mTYYs100BmRUr4=,tag:ZItcjKBKtf442Q3FjEObpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VW5zVG56VHEzTVBVQUtG
            K1V2cWszZ2JhVzhVVjIweTA1dFZvcGRZdHpnCk15enRaSzhpNWZCRENXVUc0M3g3
            bWtBdDEyUlpCOWtBWllJS1EvbXdyMk0KLS0tIERUbnBKaitvOWFoKzJoanBNRjli
            eHYyQ2I2R3lrU1plMnRhdGZxdEhmTzQKhXUDOBuL7oP9TxFJTXleLWSIA94KOJyO
            T830O25hyJDOnRWQj81PSZJ4oYI2YRvZkWCbTo8PT+chFFxGGwz1Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-25T17:40:38Z"
    mac: ENC[AES256_GCM,data:8FR2lQpHjJbeipoK4uTr6PV8m4HfwuBJq49LIwXGh/Y65D/SKDjWZQXz0GezPC7ivz9DVecGoCD64bzQ3boeaCDCb+TGQAkBecPN/26bmQczqSBhT7G+rJNtrqOUObPUhTa5+mYEPy0rVYa8pAgfiHkNYucggNgLE491ScJCyQI=,iv:GcFUdNml3oMGXJPuIS175BbrsxxyM1vB7Hk2xGko4+4=,tag:3Ttq0ydtywb4KxDuG1gdPQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
