kind: ENC[AES256_GCM,data:UaCFla09,iv:nrWUD8F5MD/s1eqlIdJyNd2n7RHTxs78+nULrM/Opvo=,tag:L4IRpfDpiedSRKc6ie8TEg==,type:str]
ansible_user: ENC[AES256_GCM,data:D8RwcyB3226S,iv:qabqmH0QK5trQU40Sk01TahY60ebkFKbA7l5ftENDaU=,tag:XzDT+03cOmSalMgi+w2jeg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:vxlvMFZs+p8GmGE=,iv:5BlWxoFf+7g/m9YEe63669OjqToNS7OavhuuV6ON/EI=,tag:eerhrhNTw+fMeRPEmstguw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTk9tR0NYMisvMCtOSytX
            SU1oTFl1ekhqV0t0Tlh5a2djeG9IVTZTZndRClcvTFdOT0tEWVN1bWVyR2cySVRM
            UG4za0dvc2tIcW5pM1lSc01TTGYwNkEKLS0tIDA2b3VlRHZzeHA3OEhpa1AycTNF
            MU5rQ2RpWWEyck53QnR6M2NPS3JFNFEKdmg4Krpj2MCsoP5M4aBHBI8sIpJFnTW8
            D8jLdj80WgMypKtQX/+ybhscUX39kNAzSqFIOJL1TC1N7aup6UEtxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T18:43:50Z"
    mac: ENC[AES256_GCM,data:kfAwfCx5EcgwPy4ElT+pPARB/P8SVukFBSN+zAtNtC3tBJGNWqxzRDW0yGNB03OFChrpqQGpFcB4UWX8GfDytHMXry+q5nNHeK3hK9lQ/r/e20pagMowN41CE28IAXKQiKz1AkSzJq0bF7V3L9RiZ0EKTH4jotrIHfHr7Y4g+dU=,iv:FKkIIwMHcXtlvzeiTuCM7eEY5aRlpOZU+zG+TAXYeeU=,tag:kjOqXTeKnGuurijmfwedGA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
