kind: ENC[AES256_GCM,data:hslUJ4Mf,iv:feuP/mHMbKADp3d6EsSzF/x7GLmsF8FE3BxFMEDkytc=,tag:aUV9QKnbVCvjppJKpqiT5w==,type:str]
ansible_user: ENC[AES256_GCM,data:KR0EIWOaKyas,iv:pxyu3DjpjBbDzYSf6ncTs5izHPPbdjXPScqz9an5DUc=,tag:n2CvF18sdmUxf7Z8rlPHCQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:mjABh63995VWlC4=,iv:rp5cldf6DjBK7iuJLOvrpg4yb1R3KEuDyFijdDxYK1g=,tag:pHCf6hNefxuxmEA0s/zoiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMC9lY2pGY0tYTTQvMVE4
            d2VCcWYyTUk3bURycmxrQm9LcVZ3MTdGcVJnCkdpQ25PUkx3UzdOZGVOT0lHZ2pP
            Ui9NSTJoZGg1RFNJUFluL21ZU25TNW8KLS0tIGlkbUFKcGNucDRpdDFVcTNvVHhk
            ZWpubFpvK2RuQnRGWjRvNmV4YmhTQ3MKS2nGRwJV5z5X99PvaQ4ifdXqnTZ5c6oL
            VyGpX+F6RX3OEIXWpzQE+P1X6sVxhecdYteeZO5uw9kJHla6sPZ0yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T19:42:10Z"
    mac: ENC[AES256_GCM,data:S8cY6sVvOmSC/NOvutILNbxCwf/xMvvHRG6FRB3s+GaZ16DTLaIE/Gsq+1YCqJ3Z9BWUEOM4yaI7f3RXu0nTjOqYX9G5QUN3BLBM0xlbQs3U4aQB2PyWG+WidTopGyiKWV5Kjf8ZhYMEwoazJrylK2g1mcpLCvdDoqNEsTur1KM=,iv:p7bT59t7ip8dGPJ06MUOkMtWLJ6pD0hWXEoGkMBGrCI=,tag:xBa/3089tIj6vMNtHEfi1Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
