kind: ENC[AES256_GCM,data:VRpQGUAN,iv:SXkc3DKqhFrk1xnj5nEDFtwV6QHVSPDnX6r+reNkK9U=,tag:IIxmexVVg5EwPwTwSijHag==,type:str]
ansible_user: ENC[AES256_GCM,data:SqADswWo/1Ad,iv:19Qh/a82APBRVCzS48iR/7WcEndIpqVcAiB0cvZ5QhQ=,tag:kK0d5VR2ZJ6ZsorRCFq4uA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:VlFFi6npC2wv6dw=,iv:vDTCkDws6QNmOpnD0PeiAIJPkTGcdlvGX8RI2alEp28=,tag:KCpFHhjCszcEJF4+BNzV1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQzNZV1I3eXlialZ2d01X
            VCtMbGZpY21RaTd4eE9SeXl0aDVIUHNrREdNCkUvQ25MekJIcFhhZWRTSmp3Y25p
            dWttL040VjRGRVZHYkoxdFRBTUY5cDQKLS0tIFh0ckZkMlhaNVcvajNtSCs5Q2d0
            aG5pdE5YVWlSQk5FMXhVZm5OOEFSVFEKa/Wb5MInSgyLvLz2fqRgrvUv6NOlwrzq
            tVNW4f05d0XNYWJuzSiYhcFA9PG1K4rbf/jn2ENBgSuSexcmuTzdpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T20:32:12Z"
    mac: ENC[AES256_GCM,data:5496X+WaFq8eD29YsXXfY1SqCxF3NQfy9XchrbBohlU8f8Uk7uBJkgaJWwEmNvi0/0FjoPofEpNCR5SVKNfV/kSM9kKEDrhCTXIDLbi+cam6P/RLRFC8e/SXPyaQywCcmuJozJfViEROxfvJFnSxxDBlVjhn98H/xOMFfclW92k=,iv:mozGBJTGIQiidJYndHmHlXpsamCvwRb12jMamkjiL6I=,tag:7rFlUVLVqlG3SIaxjW5z/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
