kind: ENC[AES256_GCM,data:rfXZBDDK,iv:gyjDQiawJN22k5g7HO515BooAmtwd4orq3rRjWYVKLI=,tag:RCJRyRQWUPKbRbmwIaKbGQ==,type:str]
ansible_user: ENC[AES256_GCM,data:8TXneHnEAEah,iv:nmp+m/CbYUVRx3zGxRnLgxtF69lJad2OwNAiGTN8Vrw=,tag:4qGf0i8V7RUuzNay3NkWbA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:jq8LVEHlgqXx+qk=,iv:f1gxX4dG3gejp3fURglOnbpARJpim8boQ6SRgmAVe2M=,tag:egNWb/8ktuBybE6uoHnE/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWVdJYmtTOCs2UENRM0Uy
            Y3JSa1BldXJYdWtzR0JvaWtQVFhvbEttRkNrCnBSMUY1QmFUWEQ5amZuV2lnajNZ
            MUZpbUJrc3lHT3ZySnJSTStxSDZqQUkKLS0tIE1maTlzL3BTVFBlMytmTUl0bVFm
            clk0dEttMEhRTlpMVkhqTHdrMy9qVG8KPeMNgzQeEGkFuJzO6ytDsd+cG7hhrJES
            3FCL3pDuZnXFNoG2j5hMOTVVZRg1mJ6f993MuRS07tKdEPicGr1rvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-16T21:57:14Z"
    mac: ENC[AES256_GCM,data:xFpO8gqcM2eA/uVkesQAjEJb0W9xg1zaH0+M2trhzdxvaXxBhCUnHqeo8VSZpUbyXvC544HxCEFGh8ggadK9vFTsEr+GCqoQwjdN23pyi+NdgHg80AtmdiprGa3xtuWVE3lAAXJjfqztKRipL/ywi2lSUqKZlj2kDpT96CeLgJE=,iv:HsMjKt78hA8ZkbX+S4lGauAAdIYURSFhVIo0Txf8Tl0=,tag:axA5oHCobaJv4ZCUkfWqBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
