apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:/7kRqYlTyYQZgkPt0fAsirCHfLFOXjT/yll9E1zDakI=,iv:kAHVEN3yckx6UvxKr5SJ2IEr4MPdNUUiJyBhfUp7Kbc=,tag:plDnsY7YTyvzB0ZNodqJgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNlJ5RUJCUkQrM1RlTVQ1
            aEpnVDFNekluWlRFaHpOV2tjSzdNcDVTUnhFCitSUzljWkZQRG5wUHFvcTZlK2p4
            cS9GRGFzWWw4MWY5UDlneGpwM05JQm8KLS0tIDBGZ2VQdm5ibXkvRm8wdDZLWHdp
            eUNLdVhRdm9oSWEwVjJrdHNITzA1emcKHCP8OqcBg/Ea2YXf43rnGnHstPcYOeZ5
            4LtgbRZFk1WzuwdG0M4vxHOlYH9NIkgWZosk1ftiYst58LWd4aWd0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T20:59:21Z"
    mac: ENC[AES256_GCM,data:z/FQNUKbrjc4skF4+DTgTSvJREcLL8P+Cv+UYTRaPdxwWurx3qxHyjlUs+suARizHhBuWM5n1cyiRshYLO57oyjFe81T4lFcHElfMvjHtZ71PpcmUjnJUpiP2uer2gusFbe8Xe8/0XrElFT1PwPIlBu4jv5Tm6g0lBZsFnT1B9k=,iv:VNJiSDGXQV1H8T8iroPqFnBBPVYn3QREvrP7GwnxV+o=,tag:NZHHqzW6fuvEGM8JRAAFdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
