---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 10.0.0.50
        k8s-1:
          ansible_host: 10.0.0.51
        k8s-2:
          ansible_host: 10.0.0.52
    worker:
      hosts:
        k8s-3:
          ansible_host: 10.0.0.53
        k8s-4:
          ansible_host: 10.0.0.54
        k8s-5:
          ansible_host: 10.0.0.55
