apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:0LD1OF417WAiwyY3N4fLnv8YDICoBu//7pM=,iv:WKha6yoVq4eK0unbvT+L6I1e4UJbYo9lf45pVujgLnE=,tag:NEj3nL46f4v2VbuXMbh80Q==,type:str]
    api-key: ENC[AES256_GCM,data:/yMxGRyMgZdbM7JXsM8B6WSQkOEOQ2Zg6zGiGdw4hBReBSk31w==,iv:EG7NjxJ9ErxRrcPg+D9rSCYHc7BjD5ng0YoVvXHpFPk=,tag:pvSM0Zx2+OUqRbAGeqJf/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NjFXMzk3aE5rTTVTaEgx
            MzZpamF1NUg1cXhwSklhS3N4TXdjaWJtcUdjCnpWNUR5bVJiOHlQclRXVFhUV3dI
            bEYzMUJZWUcyKzErb1ovcjRpUjBTb0UKLS0tIDY5R0JKb2dlTDJqVHR1N04xRFpt
            YW5ITDVTR3B1Vm55WVR2WW54M0NLOFEKiV4bTjYbAr09sF0YVoSJq2uA1g6xMmQx
            qZ+5bjLp2dj3noNjli8pMgPFtPWarJPrLVszJn1PwkXdpZjzqEtsXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T19:42:10Z"
    mac: ENC[AES256_GCM,data:dPOSY8euI3urw8DGREKyDL8XAAg8qSffeaurdioRdzoeqCNY2tGX29TX2HAGTMktoYPZHN5p4RjhgfvxJ674y1EY1TBW78G6dk4DBbmERO6BVAuJUh64MVlp3jsh/zxBkGMt3pBN8tAjL/Q/HA+EA/2CgYk3UkKtosFjFesO2KA=,iv:xlQPVk48hb3i9jZe0eJpdPa+GM/2ezyJ/o8uiLQ1X5k=,tag:5WvTlP0Onw7S7uUW3oarpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
