apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:yYCMI/WRTQTpdecpLUqivlVDSQXskSLBRnbndr8lZi6fc+w+ySs9jwy522q3R8zGk4nlV/vSO+DGBQ3M,iv:icnZ3iWVtRIhXhBYwZ6c+H28Set6YAgQjDrrr9g5KbA=,tag:sc9PqtxW9bH95WKRU/4R/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuS0FzNm1iVFhxcDZhQ2xF
            NHMxUGVzbXhqSk0yTXlKdlVzcCtFWEM2clh3Ck81SkQ4aElYbjIyTDJkbzZ3NlRE
            R01YR1UrandJOXlWV0dEWk0rMzFKQzgKLS0tIG1KUmFIUzMwSEhJMlhnRWlGWWkr
            L3VjZmJ2a3hSSEVDeWE2MDRJM0JsVDAKHnV0x8GHhm3Yrojwtn13EtAEmd2x7TOk
            Ormdan71Ig22btLdZTYu2twquFOQatobfxL0WryVms88L1770+ASAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T18:43:51Z"
    mac: ENC[AES256_GCM,data:iG9ZiwcKYv+ObnH9Cof/IJtk9vFjGpJlRJ5zrJ9KQoYDcJPlh2X55/u0spQDHV5Y+qgWW5Trn5rL797aSQbj/53KcTZg4FFBdlWLfijv2w26/H/mGkIDRjuPn0Mhlcb96NPUbB3ajeT8NYjDSI4ob1uJAmqVwlzQdWlxv31FYsU=,iv:Nf8Q6EwXfWH+OipTwlY3Iw5txN5YT65ViGd5Mo8aQD8=,tag:7GiBzVRVeuxDxcovfFWGOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
