apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:m5P2gfipfPv2Q0+QZsnJiyul7xN/iTrkD84skm9eoTjIurih33ZZpjOAcQ4Yn4KsDPf07FQsaZmWjAU/,iv:N6+9jHN4qfMP/PDzIIxKBu5lJmOL06T2zt9WUo/jfPQ=,tag:BfWns+xXnYIzNkKokpLMGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRUJseXBSYVQzYzgzMVdH
            NXRyVUZrWlo4c09yREhIYkNEVXltd2JwMEFFClhMTzBURnV4Q2NwcWp3aGpVR2w5
            RngwbzYzd1ExSjgvb2pTczNZMXRuVUEKLS0tIFVhMVlnbWZqcmpwNTdEQURsR3hw
            V21ITU1aSzVUTElEbFpxcTNVS0ZLZ00KNn+gyC37oVlUSVGXt/QlB5yrIP605p3g
            4svrSYJFQQ6AQwNo5CtZBWANwOPSaTcl8bw4GGHn4h67Ytcf9i5X+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T20:32:13Z"
    mac: ENC[AES256_GCM,data:BnXHRTafIpLno3s4X98B7PK5E2lx42AsbXYdLQrFOTGBDHHk+HLafyjpQvBQY5XYVWUE5490I4Od0QiqkLSW5h3MspP7nsAwQZNqxdGMcmxeFhcmIKAjbvus/MviIv7AscPfmY16pej11w75mbo0X20GWvE0Bd7YAuxGYDjF2cc=,iv:sZGjnMBczHEuskuH8HeEeZlyezef1DLH/lCK7gYAhjk=,tag:qiLcO7OXvNeya1ifRU+qXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
