apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:w8rT6aJ7wqY3/+fqRHDn/si9qLD7HXyzfAHm0fz7HBq/JEJpIZXacqvw2UuT5qv2fKVcENWkWd8SmLFu,iv:0++o4u/8ZGzmrkRWq3oJ8ZQaELA6O0IrgRl1OstpI5g=,tag:Oc3cktajTlZ7mM5WW4IHPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NWpERlBZM3haK2ZxdmEr
            RnZJc3YyV045QW9GOUJFOHVpVW1jOEhMUTJFCjN5bm0wRlM4RUtLQndhWEo1TEZl
            RHBtRjloMkVRdFJJMUlSbDAvUjJpLzQKLS0tIFpPM3VibVVRZVhNU1JkcUFTajkv
            UXcwZjU1c3Y2UGFJS1RDeGRDZ2ZGdE0KlhIxXcGGEXJWjs2VjgpGNVcYK6s0TIX9
            DL67tCSHimCXUW4wi7+ITANA/QlvHXUmIUz3LvjLX3jA8EUXXq4lOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-24T02:46:22Z"
    mac: ENC[AES256_GCM,data:V8WivoLKV0C5Dm39BqAHF4tApWa/Hz66fMVuM332vN6GkifZz52WP2vRzq694tZqMrHyCVSayufMtEPtVWb37MOkxQLXOJttSRoiYCctU0pKjy+YXusa37KEKuxHiS7ZdAnnOcz45ZyVRPw73Pz7dOp2odn7jkLaA4mGoQ+u6WU=,iv:dbar/F4DVr+OcfikHtv7361txxVY8vgR/lWCePrE7H8=,tag:pYuT6TjWRYkwJz0w8RA4bQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
