apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:gfhk1EHb2ty3D9c1DAWcfXZOHHGNQFkskF/0L5MpAMVUa1U/oBNeJE9NeVkUW0lmf0nfeGMBu4aAhBfA,iv:liwssAnuu2N6BTSgRtPxfHKlMgIQhiMCbNJrbtoXs4Q=,tag:IWw9S5fiSsr1eY82wCeGHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YjNvMmE2WWsrL0JRRWdI
            c2tsRTlPUk1WUGo0ZGdsNmo3UE43UEJ6K2xBCjBLbVA5akpMK2JETFRQVll0dXpn
            dTVkeGZLY0lqcmtKbWNOV29MdEw3YmMKLS0tIDI2bWtEaTdEUC9uNHRCaElFOCtH
            RTVTVXhBOWo1K1FOdzQzS2dXcmlLOW8KUDUd/cIrlM26m2tlO9NWY4yqh87qPwBT
            JCKNNp/onBLB0EsBM/d3HUAvuQVLvOHiUdgVSxk+Ra8GKGef7ChuVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T19:42:11Z"
    mac: ENC[AES256_GCM,data:qmd9s384qmEYjSJ879bVm/VgYV2Es2GoKo25E6YdTr43A9J6LVihR91aOILwWHn6e8p+4zkgDFPlv9cH0V+j393ycFPXBR6XDhBy8DSvV3eQthxPJ2msN2LG3RggSXXOVxOTN7vCtssereq330QUCF2/ue0iHu8yH4SJq5tVo6Q=,iv:OjdvwhgA+7jztcA/PlJzeRc6RpaXXOjWMdCYw/DCkko=,tag:WMTBL4yw9fMjmXjpTCM7kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
