apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:BVJimZVU6Lva27YplDkgCvj4NSAFtiFn1NlsgJsU5slJ0N82BfEhVA3qafPUg0TKLhHeDm53zqQS2qYO,iv:/GVtUh1MCG+1f9OW/pRfmJ3RuMKHD7JxH7cPdZJYxLY=,tag:L2CwojYsDyaykD2R/mxDvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3R1VhTnRsSGZSbFVCK0hZ
            ZXJ3QlNVSGpFZVRSYloydStBT1phWU5qUHl3CjFGanJFU2dPR3EybmVRaU9NbXNt
            dHZPSUt2T2pFRXJRaVJnYWo3OGxSeDgKLS0tIHpxa2hHdld0UGtWVlk2ZXF2SVRk
            RmVBUW5jL25OSGtnRTIwV1B1eGpXaGsK0WjlFNr2xB7CIO55iKddaDdyC81JmXF+
            ogF3O0ZGoOTD9aSlmOCCrbT/M1k1H99NaNY8iibV+ZZIpnOBzaPjyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T20:59:22Z"
    mac: ENC[AES256_GCM,data:pJzVfPyZGxGZlN8eH0OCCMAn/H8mOQVXWFZUS0LIlb//aQWNfbMt94aX1ix0pWr2SjaOyM0uPPZ3vAiJ6FtWN0nQ+EVf2WGZhYv8ueENn+yuIkrmafICdY1vXEzxjbbg0Rzdlt/ssfV+6FnaSFFOV4PrUP/UHcyIYuMoSRWk3eI=,iv:qG2LTamn20k/mPTDeJsgdvJHaT0teBL7DJE7rNHM1fg=,tag:dADg/Epf1AHfAXR7tVEtSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
