apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:xPjza7DEqIyZasEvoU3LniWzyjgWWXjinkEK4Vpu1k6bgG0ysMBf74PgZzExNToZP5TGnBsHo6xqIJvX,iv:Kenk4MFeC3Ufsz9I61BwVKC/Yec8WsIfxMZMtMRjC1U=,tag:FshfX+UfPq8uNd4O6DuEgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiME9Wb0tXckhSUmNmOTZU
            VUZLR1NnbEJGK2dLbzFDOThBMXNSMjRNN3lnCkZGU2YzNXRKNTZzRUtzZ1Bkb0lL
            cDhZaCsrZ3lFdlhVYmhhbk0rV2l6TncKLS0tIDZpOGE5VWdpTXFaTDF3NGNTbDM1
            MnlqMkF3cndzdEU4MnlEeFBTVU1GSEEK2e3r+goyXuQfX8D61YYUFgu7A4Q/rX1y
            rLOnXDKJcjeDmTP2UcnGeTMiGlC3oHACTYB7e9mQqvPkPvebm/Mv9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-16T21:57:15Z"
    mac: ENC[AES256_GCM,data:KvOfS0pvoioRNHTOhkzv+f2+6VmGl75AsYuZlExp7r87CioGVwtahPr9nyxXb5PbGArXFxAe7Jo6LeJmZ7QaloD/0la45xOggFtQN2EJMoAhfKg/iVDJUUVQ7jxrnlotDu9VkMnPQKXkqMd2gNUFhDtU0RviE+GrLF9XeQ4QLLk=,iv:GpiMdBqv8eb9ncriyn3xTGvAat2Z5ruwf30oauwMDQk=,tag:TSGex0oC0w6ggqVpE+D/Ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
