apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:0ylu4xiuRteNiqMo03nTEiIE8zt0B6P7CmksYXyAaE6CYzyY9qm0RXpZQCcLmShUwjytiWmYEEWWxSIh,iv:NkcOt6/VfY+jdg79SGp6Ff2lV60D17ZaQi0PG7r2jFw=,tag:5+zwBxmGd3APdNal/VDk7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkODdtWVlsTHJBSWtMaENt
            WHNoVUxRdENpM1hHZGxHMDd3ek9YWWJGNFdNClZOTTM2a09FaWVXSGNqY1NrcXhV
            am1TTUhkY2V1b290Q21PeUhCemhBeE0KLS0tIHVlUjdjUmU2SVNYUTlaZFZQWjZp
            QjBOMWJsaEpyVEs0Q1BQSWdXK0VRWjgKMET1rEWthwngRC24lcXNUvmmNOjvgh4w
            GNjQvaM73k5mEBMmNE1DBlMZLAQvLYOikC4D7ye8y1oLppcCy1Nskw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-25T17:43:33Z"
    mac: ENC[AES256_GCM,data:ODZv1nHLJepIKjEJro3Nasj/YLlV9vvXMQcVfQAvuDnPl6u/IXr0ByjBh/WJHVX7VotlkNwQ8KGGJQrMUV+D2i4U+UyTIBkdSWLtITu0XatRh2NWBwhdjSAGZgM422PmJ214Koq7DEBGIN668S4yz1Ea2OB6gTS1GBOosRNWVbM=,iv:/ToiVVLv+Sw9NDzhRvyLxnOd5gseUmtAMj9rijmNU9Q=,tag:q1VH8D4BBn62c620OMQbkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
