apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:Dt0CJaIiPKW/DmtjtFHPemgAtsbbwV2NZGuwHptf0GxFcL1ysWaLW6dq2n3z5V4uD62/ceL6lfoNdy+a,iv:BUdUsKMZQGjjjdRfuet5PcjtMK6939qQfFHB6bhkyBA=,tag:10zpsAE05VvUbfrNcTnKnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOEYrRTIrZHNHV0YzVy8x
            UVE3OUxBb1lsaTJlbXFtUHc0Zi9hQUdMUHlZCklRbnNwaWFFZ2RiZjFoWXNPYTlQ
            S1N6cytDbm8wQUtnYXU4NjNKSG9SZm8KLS0tIG02RHBJWU1IMFZCVmtHVkpic2ly
            TWVoOE5YUlZJdXJScURvdU1IcU5rYjAKfHoxgR5bvYPxvkn6jgux4iELg3TiVHoS
            vlfBptvrDQQYzG8IdLpnzjTekfV56mYzQ3utnLMj9qkgER8MNL4zoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-25T17:40:39Z"
    mac: ENC[AES256_GCM,data:JszUvICc6fnQMSU5DCJ1crs+jPRPzu4NLHstUYTvWHqjHIbIlBxJlpv/wpAWEKDooXPZ6RLosCBRzNBjwZt/YcAS6HYD++yGjyhLjADYGJQS07FQFQoOsfpW+Z7hFGJSw3meLRkcryMdHCtfYtdkhTeduJjPf4L8eUb5doR+tUo=,iv:EmC7FwzkBUYyVWC3lEliGkW+PlFSiTvO4psp/jP75js=,tag:eo5MNHjBDbCp6R2y2ZrEUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
