apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZzF4diIWmehm4EFkSg==,iv:w3EasNQFD5C0sbVXNj+IE1cdjdOAeDSsdpRDCnnlFEs=,tag:sOxDSHnZNxbxC9gmtDAFcw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:gsvDGpAM3Pr6OsZ/s0k4lIzTeXg4hoYITwE=,iv:6wQYSezsL5blol43q/FaWhtpFDZNxHno3eZ8CmiRfFI=,tag:1Ff820pxDfcJSO8dEGvpBw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:k3yJc21M6oI9XyUrNcghNc76JmHcQGWpvUZxNtUM7u1NvGd7,iv:YCGMQzlc/bCJEJNMdBWd+2m1pUilbr6BfvEzcdydorU=,tag:JZgNoPeeo7bnCkPR43B0Fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNFRRTjVSM1lNQzhmejFO
            Ym1nNkNZMjJGL2JpaUNmRmN0Vkhmb01zT0RvCjFaeUNLZWtEbkMxYnpFWkNiMWx0
            VXZ5OVhrTFVJaXRreDAyaU9rWEhFa3MKLS0tIHdtdm00OE5GQ2QzcGFRQjJQNnc4
            SU5pVWNPUnlCd2Q3OCtrT1VjYkFDYm8KQ4E8tJ28OGimV5NsTGak6cZA7T7D4owp
            Or7+FXnJbewSIDv15lcULtIxilQbf/lEdavuQ9xfdhC3m9QPf0TVFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-24T02:46:21Z"
    mac: ENC[AES256_GCM,data:QQbIKkQ9x/SclFHcLqkmkfTuGSc00lAAmsCbg87QshmPNta0wFMAnTh3JwYKS9Ow5BW+pug2dImZ/CaCfOARCXkcoFyMzXYyQ893ZZuvucyloxJZIBL2PUlOgIxSAHG0DDGZYTTI87a/YNzq+OnElKDAPz4+JNSQZ89Pj/K01iM=,iv:8v9SMuvbgnJNCNl/sGuH86roQ+RmHqPa8vZkrP6NM0k=,tag:W+wWSK4+5VWvGs8sC7tvjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
