apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:95JeYEvYZO514s5S/g==,iv:gSoBZ1hlCCkAbeKwNL8J8pE5Eq4asXPe6WdpKSXlqQ0=,tag:IgX21bGa/pPK/J/HF76YZw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ayHCNJNiQNVJ2bUy/xg6f6AGFMo+t5oVIqw=,iv:TZNn6WJpluGSpJ0ovXlje0ZUnCML+7/siYFN+aDJ7k0=,tag:A+3cnehSPbadAchch3smTg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:RP9jL78Ep9yg/lv7pngvwXMx7wCpAmkMESe+yrfWK+DqRVPZ,iv:DmBnre2v9uw0o0ThX9NcIjDSw+OJkrBYv1kmcm/qwSI=,tag:MSIRW0avw7af+u8auTiwzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaVg3eFNlSW1oQ21GNCsz
            Nngya1REU3FVcHJhMC9WZVVsNWpWRzF0aUNZCkdsY0lEUlNEMHlHbHFlYmU2b0c2
            UExZcGVzN0Z0VFg1M1pTOGNZcjNoS1kKLS0tIG12TlMweEFDeUwvMzlDMDVFa0xz
            M1E3bm5mOEo3OFEydFFES24wdmZQWmcKqcyJ8ICMmI9bfekAVtZgrNCSzHRopis+
            Fss/xhplN0D+X146l+dkdBjpAZq6DI/UQAyTFQ7pqRlmlrn03+yAYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T20:59:21Z"
    mac: ENC[AES256_GCM,data:OvGFuNsIjbKdRMGxgZPg0gsQgvaqsEcOtuFBfNl+4JpXauxV/AJF2xyuxKm07rTtILBzeMmJ+wLOSZIYvBaQz8AbeGIufpw+U9zdXoUtdCms2e7gIg0jxO1eOzAOwUWvoBo/N4uDl/7pTQpB3WpNf+gbM6tkZOmNtmPTEhPrdyA=,iv:vxXQmsUGNKy8a4bUROEhWM3BhVUMNcNSyShKWnv6m+4=,tag:RHu5VJn1cd4G+tSE8IkO4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
