apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-secret
    namespace: storage
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ViNnCxxG,iv:8wiKau84pPeLKUhkTVIqfGIaj4FB0D1iws5uwglKhgc=,tag:zAoR76nKt56fBmp/QZ6ZnA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:YD/AgjsMoGbBMDMMooU+5W53xwqRhlZrpwFWW3Gb9og=,iv:oekbcqM+d7n8m7TE+VOWFzwofbFjjUytz/pGNPuabEc=,tag:7wMHqJ1PZpgmIzZbgOUNww==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:3MuJwFDqgLiHRG1eFrycUcs0bNI=,iv:SrW9Qx9CWywsy62qI7CrOpm5BPXjUrSC0fEV2ig5+h0=,tag:bKvYoazAVMJ4yT/s1oqpwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQVJiTjVzWVY1WmJlcjI0
            c1ZZTWc1UTFUbVpSN1lFTWN3djN1MWNGVzJVCko3MWM2d0FhWHpyNmlCVEU0bnVm
            cGxkT0FpU0pXYW16Y29YKytoTTJnUW8KLS0tIGN2cWRsMjFsNG5mSVFuSHRUOWZS
            S01SM3JpYzJpVmlGZlJoNnk0V2NKMnMKTRzT32GvOBViJinxfFJdwfR9QL6rbs2w
            izPiuJPZivB1Rttfwt+RlpyyP3JFra9iK0ItN/IqluBnRi4VdMo8jA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-19T02:26:06Z"
    mac: ENC[AES256_GCM,data:LSRba4XWwg2daWz70+TuUF1hJbuIKI/9oDbP1GCwYbp3A0o1E/9unpZY4XObtEWbIVAXf7dmH/K9atY4R3QNMu3SFUAhoyj8leDUJ4EtkibbVB6qnB67w6eoGxATOSHwuerLlmfQyr1IFX6GvaFKY2dntTV53IdIV9+YK5Xdrsg=,iv:Yw4qxwvIkMCBYOE6n65SHA9UFaxKfbM0cLPGvmPpyMg=,tag:WWIw/sA6NKbewKmkxOTILw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
